import { useEffect, useMemo, useRef, useState } from 'react';
import { useRegisterSW } from 'virtual:pwa-register/react';
import { artifacts, items, maps, monsters } from '@mackerel/content';
import { DEFAULT_SETTINGS, type Campaign, type GameMode, type GameSnapshot, type Settings } from '@mackerel/shared';
import { calculatePayroll, createCampaign } from '@mackerel/simulation';
import { GameHost } from './game/GameHost';
import { MobileControls } from './components/Controls';
import { audio } from './lib/audio';
import { CoopConnection, createRoom, findRoom } from './lib/network';
import { exportSoloSave, importSoloSave, loadCampaign, loadSettings, saveCampaign, saveSettings } from './lib/storage';
import { useGameStore } from './store/gameStore';
import './styles.css';

const dailySeed=()=>Number(new Date().toISOString().slice(0,10).replaceAll('-',''));
const randomSeed=()=>Math.floor(Math.random()*2_000_000_000);
const slotLabel=(snapshot:GameSnapshot|null,playerId:string,key:'left'|'right'|'inventory')=>{const p=snapshot?.players[playerId]??(snapshot?Object.values(snapshot.players)[0]:undefined);const item=p?.slots[key];if(!item)return '비어 있음';return items.find(i=>i.id===item.contentId)?.nameKo??artifacts.find(a=>a.id===item.contentId)?.nameKo??item.contentId;};

function Panel({title,children,className='' }:{title?:string;children:React.ReactNode;className?:string}){return <section className={`panel ${className}`}>{title&&<h2>{title}</h2>}{children}</section>}
function Back({to='menu'}:{to?:Parameters<typeof useGameStore.getState> extends never?never:string}){const setScreen=useGameStore(s=>s.setScreen);return <button className="ghost back" onClick={()=>setScreen(to as never)}>← 뒤로</button>}
function FishLogo(){return <div className="fish-logo" aria-hidden="true"><div className="helmet"/><div className="fish-eye"/><div className="fish-stripes"/><div className="fish-tail"/></div>}

export default function App(){
  const store=useGameStore();const connection=useRef<CoopConnection|null>(null);const [nickname,setNickname]=useState(localStorage.getItem('mackerel-nickname')??'고등어 사원');const [joinCode,setJoinCode]=useState(new URLSearchParams(location.search).get('room')??'');const [recoveryCode,setRecoveryCode]=useState(localStorage.getItem('mackerel-recovery-code')??'');const [seed,setSeed]=useState(randomSeed());const [toast,setToast]=useState('');
  const {needRefresh:[needRefresh,setNeedRefresh],updateServiceWorker}=useRegisterSW({onRegistered(){},onRegisterError(){}});
  const say=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2300);};
  useEffect(()=>{void (async()=>{const settings=await loadSettings(DEFAULT_SETTINGS);store.setSettings(settings);audio.update(settings);const campaign=await loadCampaign('solo');store.setCampaign(campaign);store.setScreen(joinCode?'coop':'menu');})();const online=()=>store.setConnection('good'),offline=()=>store.setConnection('offline');addEventListener('online',online);addEventListener('offline',offline);const visibility=()=>document.hidden?audio.pause():audio.resume();document.addEventListener('visibilitychange',visibility);return()=>{removeEventListener('online',online);removeEventListener('offline',offline);document.removeEventListener('visibilitychange',visibility);connection.current?.leave();};},[]);
  const click=async()=>{await audio.unlock(store.settings);audio.play('ui');};
  const beginSolo=async(mode:GameMode)=>{await click();const existing=mode==='solo'?await loadCampaign('solo'):null;const campaign=existing??createCampaign(mode,seed);store.setCampaign(campaign);store.setMode(mode);setSeed(mode==='daily-solo'?dailySeed():randomSeed());store.setScreen('briefing');};
  const setupConnection=(conn:CoopConnection)=>{conn.onLobby(players=>store.setLobbyPlayers(players));conn.onSnapshot(snapshot=>store.setSnapshot(snapshot));conn.onStarted(()=>store.setScreen('game'));conn.onCampaign(({campaign,payroll,recoveryCode})=>{store.setCampaign(campaign);store.setPayroll(payroll);localStorage.setItem('mackerel-recovery-code',recoveryCode);});conn.onError(say);const activeRoom=conn.room;activeRoom?.onDrop(()=>{store.setConnection('reconnecting');say('연결이 불안정합니다. 20초 동안 자동 재접속합니다.');});activeRoom?.onReconnect(()=>{store.setRoom({reconnectToken:activeRoom.reconnectionToken,localPlayerId:activeRoom.sessionId});store.setConnection('good');say('근무 현장에 재접속했습니다.');});activeRoom?.onLeave(code=>{if(code!==1000){store.setConnection('poor');say('재접속 시간이 만료되었습니다. 마지막 완료 Day는 복구할 수 있습니다.');}});};
  const handleCreate=async(options?:{recoveryCode?:string;daily?:boolean})=>{try{await click();if(!navigator.onLine){store.setScreen('offline');return;}store.setConnection('connecting');localStorage.setItem('mackerel-nickname',nickname);const campaignId=store.campaign?.id;const result=await createRoom(nickname,{...(campaignId?{campaignId}:{}),...options});const conn=new CoopConnection();await conn.connect(result.reservation);connection.current=conn;store.setRoom({roomId:result.roomId,roomCode:result.code,reconnectToken:conn.room?.reconnectionToken??result.reconnectToken,recoveryCode:result.recoveryCode,localPlayerId:conn.room?.sessionId??''});localStorage.setItem('mackerel-reconnect',JSON.stringify(result));localStorage.setItem('mackerel-recovery-code',result.recoveryCode);setRecoveryCode(result.recoveryCode);setupConnection(conn);store.setMode(result.mode);store.setCampaign(result.campaign);store.setConnection('good');store.setScreen('lobby');}catch(e){store.setConnection('poor');say(e instanceof Error?e.message:'방 생성 실패');}};
  const handleJoin=async()=>{try{await click();if(!navigator.onLine){store.setScreen('offline');return;}store.setConnection('connecting');localStorage.setItem('mackerel-nickname',nickname);const result=await findRoom(joinCode,nickname);const conn=new CoopConnection();await conn.connect(result.reservation);connection.current=conn;store.setRoom({roomId:result.roomId,roomCode:result.code,reconnectToken:conn.room?.reconnectionToken??result.reconnectToken,recoveryCode:result.recoveryCode,localPlayerId:conn.room?.sessionId??''});localStorage.setItem('mackerel-reconnect',JSON.stringify(result));localStorage.setItem('mackerel-recovery-code',result.recoveryCode);setRecoveryCode(result.recoveryCode);setupConnection(conn);store.setMode(result.mode);store.setCampaign(result.campaign);store.setConnection('good');store.setScreen('lobby');}catch(e){store.setConnection('poor');say(e instanceof Error?e.message:'방 참가 실패');}};
  const finishGame=async(sim:import('@mackerel/simulation').GameSimulation|null,snapshot:GameSnapshot)=>{if(store.mode==='coop'||store.mode==='daily-coop'){if(!useGameStore.getState().payroll){useGameStore.getState().setPayroll(calculatePayroll({recovered:snapshot.recoveredValue,quota:snapshot.quota,contractReward:snapshot.activeContract?.rewardMultiplier??1,rescued:0,streak:store.campaign?.streak??0,facilityDamage:0,coolingUsed:0,cartDamage:0,success:snapshot.success}));}store.setScreen('results');return;}const campaign=store.campaign??createCampaign(store.mode,snapshot.seed);const payroll=sim?.payroll(campaign.streak)??calculatePayroll({recovered:snapshot.recoveredValue,quota:snapshot.quota,contractReward:snapshot.activeContract?.rewardMultiplier??1,rescued:0,streak:campaign.streak,facilityDamage:0,coolingUsed:0,cartDamage:snapshot.cart?100-snapshot.cart.health:0,success:snapshot.success});store.setPayroll(payroll);const next:Campaign={...campaign,day:snapshot.success?campaign.day+1:Math.max(1,campaign.day),salary:campaign.salary+payroll.total,streak:snapshot.success?campaign.streak+1:0,warnings:snapshot.success?campaign.warnings:Math.min(3,campaign.warnings+1),lastSeed:snapshot.seed,tutorialComplete:true,codex:[...new Set([...campaign.codex,...Object.values(snapshot.monsters).map(m=>m.contentId)])],updatedAt:new Date().toISOString()};store.setCampaign(next);if(store.mode==='solo'||store.mode==='daily-solo')await saveCampaign(next);audio.haptic(snapshot.success?[40,40,120]:[180,80,180]);store.setScreen('results');};
  const startNext=()=>{setSeed(randomSeed());store.setSnapshot(null);store.setPayroll(null);store.setScreen(store.mode==='daily-coop'?'menu':store.mode==='coop'?'lobby':'briefing');};
  const currentMap=useMemo(()=>maps.find(m=>m.id===store.snapshot?.mapId)??maps[(Math.max(1,store.campaign?.day??1)-1)%maps.length]!,[store.snapshot?.mapId,store.campaign?.day]);
  return <main className={`app quality-${store.settings.quality} ${store.settings.highContrast?'high-contrast':''}`} onPointerDown={()=>void audio.unlock(store.settings)}>
    {toast&&<div className="toast">{toast}</div>}{needRefresh&&<div className="update-banner">새 버전이 준비됐습니다.<button onClick={()=>void updateServiceWorker(true)}>업데이트</button><button onClick={()=>setNeedRefresh(false)}>나중에</button></div>}
    {store.screen==='loading'&&<div className="loading"><FishLogo/><h1>출근 준비 중…</h1></div>}
    {store.screen==='menu'&&<div className="screen menu-screen"><div className="title-zone"><FishLogo/><p className="eyebrow">심해산업 제7회수팀</p><h1>고등어 회사</h1><h3>오늘도 두 마리 출근</h3><p>욕심은 자유입니다. 벌금은 의무입니다.</p></div><div className="menu-actions"><button className="primary" data-testid="solo-button" onClick={()=>store.setScreen('mode')}>근무 시작</button>{store.campaign&&<button onClick={()=>{store.setMode('solo');setSeed(randomSeed());store.setScreen('briefing');}}>이어하기 · Day {store.campaign.day}</button>}<button onClick={()=>store.setScreen('settings')}>설정</button><div className="mini-row"><button onClick={()=>store.setScreen('codex')}>도감</button><button onClick={()=>store.setScreen('credits')}>크레딧</button></div></div><footer>WASD / 방향키 · Q/E 손 · F 상호작용 · Space 대시</footer></div>}
    {store.screen==='mode'&&<div className="screen center"><Back/><Panel title="근무 형태 선택" className="wide"><div className="mode-grid"><button className="mode-card" data-testid="solo-mode" onClick={()=>void beginSolo('solo')}><b>야간 단독 근무</b><span>자동 냉각 카트 · 오프라인 가능</span></button><button className="mode-card" onClick={()=>store.setScreen('coop')}><b>2인 공동 근무</b><span>온라인 협동 · 공유 냉기 호스</span></button><button className="mode-card" onClick={()=>void beginSolo('daily-solo')}><b>일일 도전</b><span>{new Date().toLocaleDateString('ko-KR')} 고정 시드</span></button></div></Panel></div>}
    {store.screen==='coop'&&<div className="screen center"><Back to="mode"/><Panel title="2인 공동 근무" className="wide"><label>사원명<input value={nickname} maxLength={16} onChange={e=>setNickname(e.target.value)}/></label><div className="coop-grid"><div><h3>새 근무조</h3><p>6자리 코드를 만들어 동료를 초대합니다.</p><button className="primary" data-testid="create-room" onClick={()=>void handleCreate()}>방 만들기</button><button onClick={()=>void handleCreate({daily:true})}>오늘의 2인 도전</button></div><div><h3>기존 근무조</h3><label>방 코드<input inputMode="numeric" pattern="[0-9]*" maxLength={6} value={joinCode} onChange={e=>setJoinCode(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label><button disabled={joinCode.length!==6} onClick={()=>void handleJoin()}>참가</button><label>캠페인 복구 코드<input maxLength={10} value={recoveryCode} onChange={e=>setRecoveryCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''))} placeholder="XXXXXXXXXX"/></label><button disabled={recoveryCode.length!==10} onClick={()=>void handleCreate({recoveryCode})}>복구 근무조 만들기</button></div></div></Panel></div>}
    {store.screen==='lobby'&&<div className="screen center"><Panel title="공동 근무 대기실" className="wide"><div className="room-code"><span>방 코드</span><strong>{store.roomCode}</strong><button onClick={()=>{void navigator.clipboard.writeText(`${location.origin}?room=${store.roomCode}`);say('초대 링크를 복사했습니다.');}}>초대 링크 복사</button><small>복구 코드 {store.recoveryCode}</small><button onClick={()=>{void navigator.clipboard.writeText(store.recoveryCode);say('복구 코드를 복사했습니다.');}}>복구 코드 복사</button></div><div className="crew-list">{store.lobbyPlayers.map((p,i)=><div key={p.id}><span>{i===0?'방장 ':''}{p.nickname}</span><b>{p.connected?(p.ready?'준비 완료':'대기 중'):'재접속 대기'}</b></div>)}</div><div className="row"><button onClick={()=>connection.current?.setReady(true)}>준비</button><button className="primary" disabled={store.lobbyPlayers.length<2||!store.lobbyPlayers.every(p=>p.ready)} onClick={()=>connection.current?.start()}>출근</button></div><p className="hint">연결이 끊겨도 20초 동안 동일 캐릭터 상태로 재접속할 수 있습니다.</p></Panel></div>}
    {store.screen==='briefing'&&<div className="screen briefing"><Back to="mode"/><Panel><p className="eyebrow">DAY {store.campaign?.day??1} · 출근 브리핑</p><h1>{currentMap.nameKo}</h1><p>{currentMap.description}</p><div className="brief-grid"><div><span>예상 할당량</span><b>₩ {Math.round(currentMap.baseQuota*(store.mode.includes('solo')?.69:1)).toLocaleString()}</b></div><div><span>시설 위험</span><b>{currentMap.hazard}</b></div><div><span>특수 지시</span><b>{(store.campaign?.day??1)%5===0?'엘리트 감사일':'초과 달성 권장'}</b></div></div><div className="loadout"><h3>기본 지급 장비</h3><span>소나 탐지기</span><span>휴대용 랜턴</span><span>즉석 냉각팩</span></div><button className="primary huge" data-testid="start-day" onClick={()=>store.setScreen('game')}>현장 진입</button></Panel></div>}
    {store.screen==='game'&&<div className="game-screen"><GameHost mode={store.mode} seed={seed} day={store.campaign?.day??1} playerId={store.localPlayerId||'solo-player'} nickname={nickname} duration={new URLSearchParams(location.search).has('e2e')?35:undefined} getNetworkSnapshot={store.mode==='coop'||store.mode==='daily-coop'?()=>useGameStore.getState().snapshot:undefined} sendInput={input=>connection.current?.sendInput(input)} onSnapshot={store.setSnapshot} onFinish={(sim,s)=>void finishGame(sim,s)}/><Hud/><MobileControls solo={store.mode==='solo'||store.mode==='daily-solo'}/>{!store.campaign?.tutorialComplete&&<Tutorial/>}</div>}
    {store.screen==='results'&&<Results onNext={startNext} onShop={()=>store.setScreen('shop')} onMenu={()=>store.setScreen('menu')}/>} 
    {store.screen==='shop'&&<Shop say={say} onDone={startNext}/>} 
    {store.screen==='settings'&&<SettingsScreen settings={store.settings} setSettings={async s=>{store.setSettings(s);audio.update(s);await saveSettings(s);}} say={say}/>} 
    {store.screen==='codex'&&<Codex/>}{store.screen==='credits'&&<Credits/>}
    {store.screen==='offline'&&<div className="screen center"><Panel title="오프라인"><p>2인 공동 근무에는 인터넷 연결이 필요합니다.</p><button onClick={()=>store.setScreen('mode')}>1인 근무로 돌아가기</button></Panel></div>}
  </main>;
}

function Hud(){const s=useGameStore(x=>x.snapshot),id=useGameStore(x=>x.localPlayerId),conn=useGameStore(x=>x.connection);if(!s)return <div className="hud loading-hud">현장 연결 중…</div>;const p=s.players[id]??Object.values(s.players)[0];const ratio=s.recoveredValue/Math.max(1,s.quota);return <div className="hud"><div className="hud-top"><div><b>DAY {s.day}</b><span>{Math.ceil(s.timeLeft/60)}:{String(Math.ceil(s.timeLeft)%60).padStart(2,'0')}</span></div><div className="quota"><span>회수 ₩{s.recoveredValue.toLocaleString()} / ₩{s.quota.toLocaleString()}</span><i style={{width:`${Math.min(100,ratio*100)}%`}}/></div><div className={`danger danger-${s.danger}`}><span>위험 {s.danger}</span><i style={{width:`${s.dangerProgress*100}%`}}/></div><div className={`net ${conn}`}>{conn==='good'?'● 연결 양호':conn==='offline'?'○ 오프라인':'◐ 연결 확인'}</div></div>{p&&<><div className="status-stack"><label>신선도 <b>{Math.round(p.freshness)}</b><i style={{width:`${p.freshness}%`}}/></label><label>부상 <b>{'●'.repeat(p.injuries)}{'○'.repeat(3-p.injuries)}</b></label>{s.cart&&<label>카트 <b>{Math.round(s.cart.battery)}%</b><i style={{width:`${s.cart.battery}%`}}/></label>}</div><div className="slots"><div><small>왼손 Q</small><b>{slotLabel(s,p.id,'left')}</b></div><div><small>인벤토리 R</small><b>{slotLabel(s,p.id,'inventory')}</b></div><div><small>오른손 E</small><b>{slotLabel(s,p.id,'right')}</b></div></div></>}{s.extractionOpen&&<div className="extraction-banner">할당량 달성 · 입구로 탈출 가능</div>}</div>}
function Tutorial(){const [step,setStep]=useState(0);const steps=['왼쪽 조이스틱 또는 WASD로 이동하세요.','F 상호작용으로 가까운 유물을 주우세요.','손 버튼 Q/E로 장비를 사용하세요.','입구의 녹색 구역에 유물을 입고하세요.','할당량 달성 후 입구에서 탈출하세요.'];useEffect(()=>{const t=setInterval(()=>setStep(v=>Math.min(steps.length-1,v+1)),7000);return()=>clearInterval(t);},[]);return <div className="tutorial"><b>신입 교육 {step+1}/{steps.length}</b><span>{steps[step]}</span><button onClick={()=>setStep(steps.length-1)}>건너뛰기</button></div>}
function Results({onNext,onShop,onMenu}:{onNext:()=>void;onShop:()=>void;onMenu:()=>void}){const s=useGameStore(x=>x.snapshot),p=useGameStore(x=>x.payroll);if(!s||!p)return null;const rows=[['회수 금액',p.recovered],['초과 달성 보너스',p.overQuotaBonus],['위험 계약 보너스',p.contractBonus],['동료 구조 수당',p.rescueBonus],['연속 생환 보너스',p.streakBonus],['시설 파손 비용',p.facilityDamage],['냉기 사용료',p.coolingFee],['카트 수리비',p.repairFee],['회사 발전 기금',p.companyFund]] as const;return <div className="screen results"><Panel><p className="eyebrow">근무 결과</p><h1>{s.success?'생환 완료':'근무 실패'}</h1><div className="appraisal"><h3>유물 감정</h3><div className="artifact-reveal">회수 총액 <strong>₩ {s.recoveredValue.toLocaleString()}</strong></div></div><div className="payroll">{rows.map(([label,value])=><div key={label} className={value<0?'minus':''}><span>{label}</span><b>{value>=0?'+':''}{value.toLocaleString()}</b></div>)}<div className="total"><span>최종 급여</span><strong>₩ {p.total.toLocaleString()}</strong></div></div><div className="row"><button onClick={onMenu}>메뉴</button><button onClick={onShop}>상점</button><button className="primary" onClick={onNext}>다음 Day</button></div></Panel></div>}
function Shop({say,onDone}:{say:(s:string)=>void;onDone:()=>void}){const campaign=useGameStore(x=>x.campaign),setCampaign=useGameStore(x=>x.setCampaign);if(!campaign)return null;const buy=async(id:string,price:number)=>{if(campaign.salary<price){say('급여가 부족합니다.');return;}const next={...campaign,salary:campaign.salary-price,equipment:[...campaign.equipment,id],unlocks:[...new Set([...campaign.unlocks,id])],updatedAt:new Date().toISOString()};setCampaign(next);await saveCampaign(next);say('장비를 구매했습니다.');};return <div className="screen center"><Panel title={`회사 보급소 · 보유 ₩${campaign.salary.toLocaleString()}`} className="wide"><div className="shop-grid">{items.filter(i=>i.unlockDay<=campaign.day+2).slice(0,10).map(i=><button key={i.id} className="shop-item" onClick={()=>void buy(i.id,i.price)}><span className="item-icon">{i.icon}</span><b>{i.nameKo}</b><small>{i.description}</small><strong>₩ {i.price}</strong></button>)}</div><button className="primary" onClick={onDone}>다음 근무</button></Panel></div>}
function SettingsScreen({settings,setSettings,say}:{settings:Settings;setSettings:(s:Settings)=>Promise<void>;say:(s:string)=>void}){const set=<K extends keyof Settings>(k:K,v:Settings[K])=>void setSettings({...settings,[k]:v});const file=useRef<HTMLInputElement>(null);return <div className="screen center settings-screen"><Back/><Panel title="설정" className="wide settings-panel"><div className="settings-grid"><label>음악 <input type="range" min="0" max="1" step=".05" value={settings.music} onChange={e=>set('music',Number(e.target.value))}/></label><label>효과음 <input type="range" min="0" max="1" step=".05" value={settings.sfx} onChange={e=>set('sfx',Number(e.target.value))}/></label><label>화면 흔들림 <input type="range" min="0" max="1" step=".1" value={settings.shake} onChange={e=>set('shake',Number(e.target.value))}/></label><label>버튼 크기 <input type="range" min=".8" max="1.5" step=".1" value={settings.buttonSize} onChange={e=>set('buttonSize',Number(e.target.value))}/></label><label>그래픽<select value={settings.quality} onChange={e=>set('quality',e.target.value as Settings['quality'])}><option value="auto">자동</option><option value="high">높음</option><option value="medium">중간</option><option value="low">낮음</option></select></label><label>FPS<select value={settings.fpsLimit} onChange={e=>set('fpsLimit',Number(e.target.value) as 30|60)}><option value="60">60</option><option value="30">30</option></select></label><label><input type="checkbox" checked={settings.haptics} onChange={e=>set('haptics',e.target.checked)}/> 햅틱</label><label><input type="checkbox" checked={settings.highContrast} onChange={e=>set('highContrast',e.target.checked)}/> 고대비 상호작용</label><label><input type="checkbox" checked={settings.leftHanded} onChange={e=>set('leftHanded',e.target.checked)}/> 왼손잡이 UI</label><label><input type="checkbox" checked={settings.muted} onChange={e=>set('muted',e.target.checked)}/> 전체 음소거</label></div><div className="row"><button onClick={async()=>{const text=await exportSoloSave();const blob=new Blob([text],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mackerel-company-save.json';a.click();URL.revokeObjectURL(a.href);}}>저장 내보내기</button><button onClick={()=>file.current?.click()}>저장 가져오기</button><input ref={file} hidden type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{await importSoloSave(await f.text());say('저장을 가져왔습니다.');}catch(err){say(err instanceof Error?err.message:'가져오기 실패');}}}/></div></Panel></div>}
function Codex(){const campaign=useGameStore(x=>x.campaign);return <div className="screen center"><Back/><Panel title="회사 생물·유물 도감" className="wide"><div className="codex-grid">{monsters.map(m=><article key={m.id} className={campaign?.codex.includes(m.id)?'':'locked'}><div className="codex-silhouette" style={{background:m.color}}/><b>{campaign?.codex.includes(m.id)?m.nameKo:'미확인 생물'}</b><small>{campaign?.codex.includes(m.id)?m.counter:`Day ${m.unlockDay} 이후 기록 가능`}</small></article>)}</div></Panel></div>}
function Credits(){return <div className="screen center"><Back/><Panel title="크레딧" className="wide"><p>기획·코드·절차적 그래픽: 본 프로젝트 자체 제작</p><p>런타임: React, Phaser, Colyseus, Howler.js, Tone.js, Zustand, Zod, Vite PWA</p><p>외부 그래픽 및 음원 파일은 포함하지 않았습니다. 모든 기본 시각 요소와 효과음은 런타임에서 생성됩니다.</p><p>오픈소스 라이선스는 저장소의 LICENSES_THIRD_PARTY.md를 확인하세요.</p></Panel></div>}
