import express from 'express';import cors from 'cors';import helmet from 'helmet';import pino from 'pino';import { pinoHttp } from 'pino-http';import { createServer } from 'node:http';import { resolve } from 'node:path';import { existsSync } from 'node:fs';import { Server, matchMaker } from '@colyseus/core';import { WebSocketTransport } from '@colyseus/ws-transport';import { RoomCreateSchema, RoomJoinSchema, type GameMode } from '@mackerel/shared';import { createCampaign } from '@mackerel/simulation';import { CampaignDatabase } from './database.js';import { MackerelRoom } from './room.js';

const port=Number(process.env.PORT??3000),origin=process.env.PUBLIC_ORIGIN??(process.env.RENDER_EXTERNAL_HOSTNAME?`https://${process.env.RENDER_EXTERNAL_HOSTNAME}`:'http://localhost:3000'),dbPath=resolve(process.env.DATABASE_PATH??'./data/mackerel-company.sqlite'),reconnectGraceSeconds=Number(process.env.RECONNECT_GRACE_SECONDS??20);const logger=pino({level:process.env.LOG_LEVEL??'info'});const database=new CampaignDatabase(dbPath);const app=express();app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));app.use(cors({origin:process.env.NODE_ENV==='production'?origin:true,credentials:true}));app.use(express.json({limit:'16kb'}));app.use(pinoHttp({logger}));const httpServer=createServer(app);const gameServer=new Server({transport:new WebSocketTransport({server:httpServer,maxPayload:4096})});gameServer.define('mackerel',MackerelRoom);
const directory=new Map<string,{roomId:string;createdAt:number;recoveryCode:string;campaignId:string;mode:GameMode}>();const attempts=new Map<string,{count:number,reset:number}>();
const sixDigits=()=>String(Math.floor(100000+Math.random()*900000));const recovery=()=>crypto.randomUUID().replaceAll('-','').slice(0,10).toUpperCase();const rateLimited=(ip:string)=>{const now=Date.now(),entry=attempts.get(ip);if(!entry||entry.reset<now){attempts.set(ip,{count:1,reset:now+60_000});return false;}entry.count++;return entry.count>25;};
app.get('/health',(_req,res)=>res.json({ok:true,service:'mackerel-company',time:new Date().toISOString()}));
app.post('/api/rooms',async(req,res)=>{try{const parsed=RoomCreateSchema.parse(req.body),code=(()=>{let c=sixDigits();while(directory.has(c))c=sixDigits();return c;})(),hostToken=crypto.randomUUID(),dailySeed=Number(new Date().toISOString().slice(0,10).replaceAll('-',''));const recovered=parsed.recoveryCode?database.loadByRecoveryCode(parsed.recoveryCode):null;if(parsed.recoveryCode&&!recovered){res.status(404).json({error:'복구 코드를 찾을 수 없습니다.'});return;}const campaign=recovered??createCampaign(parsed.daily?'daily-coop':'coop',parsed.daily?dailySeed:Date.now()),recoveryCode=parsed.recoveryCode??recovery();database.save(campaign,recoveryCode);const listing=await matchMaker.createRoom('mackerel',{code,hostToken,nickname:parsed.nickname,campaign,recoveryCode,database,logger,reconnectGraceSeconds});const reservation=await matchMaker.joinById(listing.roomId,{nickname:parsed.nickname,hostToken});directory.set(code,{roomId:listing.roomId,createdAt:Date.now(),recoveryCode,campaignId:campaign.id,mode:campaign.mode});res.status(201).json({roomId:listing.roomId,code,reconnectToken:hostToken,recoveryCode,campaignId:campaign.id,mode:campaign.mode,campaign,reservation});}catch(error){logger.warn({error},'room create failed');res.status(400).json({error:'방을 만들 수 없습니다.'});}});
app.post('/api/rooms/reconnect',async(req,res)=>{try{const token=typeof req.body?.reconnectionToken==='string'?req.body.reconnectionToken:'';const separator=token.indexOf(':');if(separator<1||separator===token.length-1||token.length>160)throw new Error('invalid token');const roomId=token.slice(0,separator),reconnectionToken=token.slice(separator+1);const reservation=await matchMaker.reconnect(roomId,{reconnectionToken});res.json({reservation});}catch(error){logger.warn({error},'room reconnect failed');res.status(410).json({error:'재접속 시간이 만료되었거나 방이 종료되었습니다.'});}});
app.post('/api/rooms/join',async(req,res)=>{const ip=req.ip??'unknown';if(rateLimited(ip)){res.status(429).json({error:'참가 요청이 너무 많습니다.'});return;}try{const parsed=RoomJoinSchema.parse(req.body),entry=directory.get(parsed.code);if(!entry){res.status(404).json({error:'방 코드를 찾을 수 없습니다.'});return;}const listings=await matchMaker.query({roomId:entry.roomId});if(!listings.length||listings[0]!.clients>=2){if(!listings.length)directory.delete(parsed.code);res.status(409).json({error:listings.length?'방이 가득 찼습니다.':'만료된 방입니다.'});return;}const reconnectToken=parsed.reconnectToken??crypto.randomUUID();const reservation=await matchMaker.joinById(entry.roomId,{nickname:parsed.nickname,reconnectToken});const campaign=database.loadByRecoveryCode(entry.recoveryCode);res.json({roomId:entry.roomId,code:parsed.code,reconnectToken,recoveryCode:entry.recoveryCode,mode:entry.mode,campaign,reservation});}catch{res.status(400).json({error:'6자리 방 코드와 사원명을 확인하세요.'});}});
app.get('/api/campaigns/recover/:code',(req,res)=>{const campaign=database.loadByRecoveryCode(req.params.code.toUpperCase());if(!campaign){res.status(404).json({error:'복구 코드를 찾을 수 없습니다.'});return;}res.json({campaign});});
const clientDist=resolve(import.meta.dirname,'../../client/dist');if(existsSync(clientDist)){app.use(express.static(clientDist,{maxAge:'1y',immutable:true,index:false}));app.get('/',(_req,res)=>res.sendFile(resolve(clientDist,'index.html')));app.get('/*splat',(_req,res)=>res.sendFile(resolve(clientDist,'index.html')));}
const cleanup=setInterval(async()=>{const ttl=Number(process.env.ROOM_TTL_MINUTES??30)*60_000,now=Date.now();for(const [code,entry] of directory){if(now-entry.createdAt>ttl){const active=await matchMaker.query({roomId:entry.roomId});if(!active.length||active[0]!.clients===0)directory.delete(code);}}},60_000);cleanup.unref();
await gameServer.listen(port);logger.info({port,origin,dbPath},'mackerel company server ready');
const shutdown=async(signal:string)=>{logger.info({signal},'shutdown');clearInterval(cleanup);await gameServer.gracefullyShutdown(false);database.close();httpServer.close(()=>process.exit(0));setTimeout(()=>process.exit(1),5000).unref();};process.on('SIGTERM',()=>void shutdown('SIGTERM'));process.on('SIGINT',()=>void shutdown('SIGINT'));
