import { Client, Room } from '@colyseus/core';
import { PlayerInputSchema, type Campaign } from '@mackerel/shared';
import { GameSimulation, createCampaign } from '@mackerel/simulation';
import type { CampaignDatabase } from './database.js';
import type { Logger } from 'pino';

export interface RoomCreateOptions{code:string;hostToken:string;nickname:string;campaign?:Campaign;recoveryCode:string;database:CampaignDatabase;logger:Logger;reconnectGraceSeconds:number}
interface JoinOptions{nickname?:string;hostToken?:string;reconnectToken?:string}
interface PlayerMeta{nickname:string;ready:boolean;connected:boolean;token:string;lastInputAt:number;inputCount:number;windowStarted:number}

export class MackerelRoom extends Room{
  maxClients=2;autoDispose=true;private code='';private hostSession='';private metas=new Map<string,PlayerMeta>();private simulation:GameSimulation|null=null;private database!:CampaignDatabase;private logger!:Logger;private campaign!:Campaign;private recoveryCode='';private reconnectGraceSeconds=20;
  onCreate(options:RoomCreateOptions){this.code=options.code;this.database=options.database;this.logger=options.logger;this.campaign=options.campaign??createCampaign('coop',Date.now());this.recoveryCode=options.recoveryCode;this.reconnectGraceSeconds=options.reconnectGraceSeconds;this.setSimulationInterval(dt=>this.tick(dt/1000),50);this.registerMessages();this.logger.info({roomId:this.roomId,code:this.code},'room created');}
  onJoin(client:Client,options:JoinOptions){const nickname=(options.nickname??'고등어 사원').replace(/[<>]/g,'').slice(0,16);const token=options.hostToken??options.reconnectToken??crypto.randomUUID();this.metas.set(client.sessionId,{nickname,ready:false,connected:true,token,lastInputAt:0,inputCount:0,windowStarted:Date.now()});if(!this.hostSession)this.hostSession=client.sessionId;this.broadcastLobby();this.logger.info({roomId:this.roomId,sessionId:client.sessionId,nickname},'player joined');}
  private registerMessages(){this.onMessage('input',(sender,raw:unknown)=>{if(!this.simulation)return;const parsed=PlayerInputSchema.safeParse(raw);if(!parsed.success){this.logger.warn({roomId:this.roomId,sessionId:sender.sessionId},'invalid input');return;}const meta=this.metas.get(sender.sessionId);if(!meta)return;const now=Date.now();if(now-meta.windowStarted>1000){meta.windowStarted=now;meta.inputCount=0;}meta.inputCount++;if(meta.inputCount>35)return;meta.lastInputAt=now;this.simulation.applyInput(sender.sessionId,parsed.data);});
    this.onMessage('ready',(sender,data:{ready?:unknown})=>{const meta=this.metas.get(sender.sessionId);if(meta)meta.ready=data.ready===true;this.broadcastLobby();});
    this.onMessage('start',(sender)=>{if(sender.sessionId!==this.hostSession)return;if(this.clients.length!==2||![...this.metas.values()].every(meta=>meta.ready))return;this.startGame();});
  }
  private startGame(){const ids=this.clients.map(c=>c.sessionId),names=ids.map(i=>this.metas.get(i)?.nickname??'고등어');const seed=this.campaign.mode==='daily-coop'?this.campaign.lastSeed:Math.floor(Math.random()*2_000_000_000);this.simulation=new GameSimulation({seed,day:this.campaign.day,mode:this.campaign.mode==='daily-coop'?'daily-coop':'coop',playerIds:ids,nicknames:names});this.broadcast('started',{day:this.campaign.day});this.broadcast('snapshot',this.simulation.state);}
  private tick(dt:number){if(!this.simulation)return;this.simulation.step(Math.min(.05,dt));this.broadcast('snapshot',this.simulation.state);if(this.simulation.state.completed){const payroll=this.simulation.payroll(this.campaign.streak);this.campaign={...this.campaign,day:this.campaign.mode==='daily-coop'?1:(this.simulation.state.success?this.campaign.day+1:this.campaign.day),salary:this.campaign.salary+payroll.total,streak:this.simulation.state.success?this.campaign.streak+1:0,warnings:this.simulation.state.success?this.campaign.warnings:Math.min(3,this.campaign.warnings+1),lastSeed:this.simulation.state.seed,updatedAt:new Date().toISOString()};this.database.save(this.campaign,this.recoveryCode);this.broadcast('campaign',{campaign:this.campaign,recoveryCode:this.recoveryCode,payroll});this.simulation=null;for(const meta of this.metas.values())meta.ready=false;this.broadcastLobby();}}
  async onLeave(client:Client,code?:number){const consented=code===1000;const meta=this.metas.get(client.sessionId);if(meta)meta.connected=false;this.broadcastLobby();if(consented){this.metas.delete(client.sessionId);this.transferHost();return;}try{await this.allowReconnection(client,this.reconnectGraceSeconds);const restored=this.metas.get(client.sessionId);if(restored)restored.connected=true;this.simulation?.setConnected(client.sessionId,true);this.broadcastLobby();}catch{this.metas.delete(client.sessionId);this.simulation?.setConnected(client.sessionId,false);this.transferHost();this.broadcastLobby();}}
  private transferHost(){if(this.hostSession&&!this.metas.has(this.hostSession))this.hostSession=this.clients[0]?.sessionId??'';}
  private broadcastLobby(){this.broadcast('lobby',{code:this.code,players:[...this.metas.entries()].map(([id,m])=>({id,nickname:m.nickname,ready:m.ready,connected:m.connected,host:id===this.hostSession}))});}
  onDispose(){this.logger.info({roomId:this.roomId,code:this.code},'room disposed');}
}
