import Phaser from 'phaser';
import { GameSimulation } from '@mackerel/simulation';
import { maps, monsters, artifacts } from '@mackerel/content';
import type { GameMode, GameSnapshot, PlayerInput } from '@mackerel/shared';
import { inputBridge } from './input';

export interface SceneInitData{
  mode:GameMode; seed:number; day:number; playerId:string; nickname:string; duration?:number|undefined;
  getNetworkSnapshot?:(()=>GameSnapshot|null)|undefined; sendInput?:((input:PlayerInput)=>void)|undefined;
  onSnapshot:(snapshot:GameSnapshot)=>void; onFinish:(simulation:GameSimulation|null,snapshot:GameSnapshot)=>void;
}

type Keys={up:Phaser.Input.Keyboard.Key;down:Phaser.Input.Keyboard.Key;left:Phaser.Input.Keyboard.Key;right:Phaser.Input.Keyboard.Key;w:Phaser.Input.Keyboard.Key;s:Phaser.Input.Keyboard.Key;a:Phaser.Input.Keyboard.Key;d:Phaser.Input.Keyboard.Key;q:Phaser.Input.Keyboard.Key;e:Phaser.Input.Keyboard.Key;f:Phaser.Input.Keyboard.Key;r:Phaser.Input.Keyboard.Key;space:Phaser.Input.Keyboard.Key;g:Phaser.Input.Keyboard.Key;c:Phaser.Input.Keyboard.Key};

export class MackerelScene extends Phaser.Scene{
  private dataIn!:SceneInitData;private sim:GameSimulation|null=null;private world!:Phaser.GameObjects.Graphics;private fx!:Phaser.GameObjects.Graphics;private keys!:Keys;private accumulator=0;private lastSnapshotPush=0;private ended=false;
  constructor(){super('MackerelScene');}
  init(data:SceneInitData){this.dataIn=data;}
  create(){
    if(!this.dataIn.getNetworkSnapshot)this.sim=new GameSimulation({seed:this.dataIn.seed,day:this.dataIn.day,mode:this.dataIn.mode,playerIds:[this.dataIn.playerId],nicknames:[this.dataIn.nickname],durationSeconds:this.dataIn.duration});
    this.world=this.add.graphics();this.fx=this.add.graphics().setScrollFactor(0).setDepth(100);
    this.cameras.main.setBackgroundColor('#061319');this.cameras.main.setZoom(this.scale.width<700?.72:.88);this.cameras.main.roundPixels=false;
    const kb=this.input.keyboard;if(!kb)throw new Error('Keyboard unavailable');this.keys=kb.addKeys({up:'UP',down:'DOWN',left:'LEFT',right:'RIGHT',w:'W',s:'S',a:'A',d:'D',q:'Q',e:'E',f:'F',r:'R',space:'SPACE',g:'G',c:'C'}) as Keys;
    this.scale.on('resize',()=>this.cameras.main.setZoom(this.scale.width<700?.68:.88));
  }
  private inputVector(){let x=0,y=0;if(this.keys.left.isDown||this.keys.a.isDown)x--;if(this.keys.right.isDown||this.keys.d.isDown)x++;if(this.keys.up.isDown||this.keys.w.isDown)y--;if(this.keys.down.isDown||this.keys.s.isDown)y++;const l=Math.hypot(x,y);return l>0?{x:x/l,y:y/l}:{x:0,y:0};}
  private collectInput():PlayerInput{if(Phaser.Input.Keyboard.JustDown(this.keys.q))inputBridge.pulse('leftUse');if(Phaser.Input.Keyboard.JustDown(this.keys.e))inputBridge.pulse('rightUse');if(Phaser.Input.Keyboard.JustDown(this.keys.f))inputBridge.pulse('interact');if(Phaser.Input.Keyboard.JustDown(this.keys.r))inputBridge.pulse('swapInventory');if(Phaser.Input.Keyboard.JustDown(this.keys.space))inputBridge.pulse('dash');if(Phaser.Input.Keyboard.JustDown(this.keys.g))inputBridge.pulse('drop');if(Phaser.Input.Keyboard.JustDown(this.keys.c))inputBridge.pulse('ping');return inputBridge.consume(this.inputVector());}
  update(_time:number,deltaMs:number){
    if(this.ended)return;this.accumulator+=Math.min(deltaMs/1000,.1);while(this.accumulator>=.05){const input=this.collectInput();if(this.sim){this.sim.applyInput(this.dataIn.playerId,input);this.sim.step(.05);}else this.dataIn.sendInput?.(input);this.accumulator-=.05;}
    const snapshot=this.sim?.state??this.dataIn.getNetworkSnapshot?.()??null;if(!snapshot)return;this.renderSnapshot(snapshot);
    const me=snapshot.players[this.dataIn.playerId]??Object.values(snapshot.players)[0];if(me)this.cameras.main.centerOn(me.position.x,me.position.y);
    if(this.time.now-this.lastSnapshotPush>100){this.dataIn.onSnapshot(snapshot);this.lastSnapshotPush=this.time.now;}
    if(snapshot.completed&&!this.ended){this.ended=true;this.dataIn.onSnapshot(snapshot);this.time.delayedCall(900,()=>this.dataIn.onFinish(this.sim,snapshot));}
  }
  private renderSnapshot(s:GameSnapshot){const g=this.world;g.clear();const map=maps.find(m=>m.id===s.mapId)??maps[0]!;g.fillStyle(Phaser.Display.Color.HexStringToColor(map.floor).color,1);g.fillRect(0,0,s.mapWidth,s.mapHeight);
    this.drawFloor(g,s,map.accent);this.drawRooms(g,s,map.accent);this.drawExit(g,s);for(const item of Object.values(s.items))if(item.position)this.drawItem(g,item.position.x,item.position.y,item.contentId,item.size,item.durability);if(s.cart)this.drawCart(g,s.cart.position.x,s.cart.position.y,s.cart.battery,s.cart.health);
    const players=Object.values(s.players);if(players.length===2)this.drawHose(g,players[0]!.position,players[1]!.position);else if(s.cart&&players[0])this.drawHose(g,players[0].position,s.cart.position);
    for(const m of Object.values(s.monsters))this.drawMonster(g,m.position.x,m.position.y,m.contentId,m.state,m.elite);for(const p of players)this.drawFish(g,p.position.x,p.position.y,p.facing,p.color,p.downed,p.nickname);
    for(const n of s.noises){g.lineStyle(3,0x78e8ff,n.ttl/1.4*.55);g.strokeCircle(n.position.x,n.position.y,n.radius*(1-n.ttl/1.4));}
    this.drawVignette(s);
  }
  private drawFloor(g:Phaser.GameObjects.Graphics,s:GameSnapshot,accent:string){const color=Phaser.Display.Color.HexStringToColor(accent).color;g.lineStyle(2,color,.12);for(let x=0;x<s.mapWidth;x+=96)g.lineBetween(x,0,x,s.mapHeight);for(let y=0;y<s.mapHeight;y+=96)g.lineBetween(0,y,s.mapWidth,y);g.fillStyle(0xffffff,.035);for(let i=0;i<28;i++){const x=(i*173+s.seed%137)%s.mapWidth,y=(i*97+s.seed%89)%s.mapHeight;g.fillEllipse(x,y,120+(i%4)*30,32+(i%3)*15);}}
  private drawRooms(g:Phaser.GameObjects.Graphics,s:GameSnapshot,accent:string){const ac=Phaser.Display.Color.HexStringToColor(accent).color;g.fillStyle(0x071014,.82);g.lineStyle(8,0x31444b,.9);const rooms=[{x:s.mapWidth*.22,y:80,w:230,h:s.mapHeight*.3},{x:s.mapWidth*.48,y:s.mapHeight*.56,w:300,h:260},{x:s.mapWidth*.7,y:90,w:260,h:300},{x:s.mapWidth*.78,y:s.mapHeight*.64,w:280,h:240}];for(const r of rooms){g.fillRoundedRect(r.x,r.y,r.w,r.h,16);g.strokeRoundedRect(r.x,r.y,r.w,r.h,16);g.lineStyle(3,ac,.55);g.lineBetween(r.x+35,r.y+22,r.x+r.w-35,r.y+22);g.lineStyle(8,0x31444b,.9);}for(let i=0;i<16;i++){const x=300+(i*119)%Math.max(320,s.mapWidth-430),y=100+(i*211)%Math.max(300,s.mapHeight-200);g.fillStyle(i%2?0x4b5b60:0x27363c,.85);g.fillRoundedRect(x,y,64+(i%3)*24,42+(i%2)*28,8);g.fillStyle(0xffffff,.08);g.fillRect(x+8,y+7,45,5);}}
  private drawExit(g:Phaser.GameObjects.Graphics,s:GameSnapshot){const y=s.mapHeight/2;g.fillStyle(s.extractionOpen?0x4ef2a0:0x56646a,.24);g.fillRoundedRect(20,y-185,115,370,20);g.lineStyle(6,s.extractionOpen?0x4ef2a0:0x6d7b80,.9);g.strokeRoundedRect(20,y-185,115,370,20);g.fillStyle(0xffffff,.85);for(let i=-2;i<=2;i++)g.fillTriangle(52,y+i*58,95,y+i*58-16,95,y+i*58+16);}
  private drawFish(g:Phaser.GameObjects.Graphics,x:number,y:number,facing:number,color:string,downed:boolean,name:string){g.save();g.translateCanvas(x,y);g.rotateCanvas(facing);const body=Phaser.Display.Color.HexStringToColor(color).color;g.fillStyle(0x000000,.3);g.fillEllipse(-2,16,96,42);g.fillStyle(body,downed?.6:1);g.fillEllipse(0,0,96,50);g.fillStyle(0xd9eef0,.95);g.fillEllipse(-10,10,63,22);g.fillStyle(body,1);g.fillTriangle(43,0,72,-31,70,28);g.lineStyle(4,0x0d3441,.8);g.lineBetween(-18,-15,7,-7);g.lineBetween(-10,-23,15,-13);g.fillStyle(0xffd65a,1);g.fillRect(-24,-37,45,17);g.fillEllipse(-2,-38,52,26);g.fillStyle(0xffffff,1);g.fillCircle(-35,-8,9);g.fillStyle(0x071014,1);g.fillCircle(-37,-8,4);g.fillStyle(0xffffff,.7);g.fillRect(-5,2,20,4);g.restore();this.addNameLabel(g,x,y-54,name,downed);}
  private addNameLabel(g:Phaser.GameObjects.Graphics,x:number,y:number,_name:string,downed:boolean){g.fillStyle(downed?0xff5b5b:0xffffff,.7);g.fillRoundedRect(x-24,y,48,5,3);}
  private drawHose(g:Phaser.GameObjects.Graphics,a:{x:number;y:number},b:{x:number;y:number}){const d=Phaser.Math.Distance.Between(a.x,a.y,b.x,b.y);g.lineStyle(10,d>570?0xff5c4f:0x69d8e7,.8);const midX=(a.x+b.x)/2,midY=(a.y+b.y)/2+Math.min(60,d*.08);const curve=new Phaser.Curves.QuadraticBezier(new Phaser.Math.Vector2(a.x,a.y),new Phaser.Math.Vector2(midX,midY),new Phaser.Math.Vector2(b.x,b.y));curve.draw(g,48);g.lineStyle(2,0xe8fdff,.5);curve.draw(g,48);}
  private drawCart(g:Phaser.GameObjects.Graphics,x:number,y:number,battery:number,health:number){g.fillStyle(0x000000,.35);g.fillEllipse(x,y+20,104,42);g.fillStyle(0x4c6972,1);g.fillRoundedRect(x-48,y-31,96,62,14);g.fillStyle(0x8de9f4,.5);g.fillRoundedRect(x-35,y-19,70,24,8);g.fillStyle(battery>25?0x63e79d:0xff6e55,1);g.fillRect(x-32,y-15,64*battery/100,16);g.fillStyle(0x18262b,1);g.fillCircle(x-32,y+34,13);g.fillCircle(x+32,y+34,13);g.lineStyle(4,health>40?0xdbeef0:0xff5a4c,.8);g.strokeRoundedRect(x-48,y-31,96,62,14);}
  private drawItem(g:Phaser.GameObjects.Graphics,x:number,y:number,id:string,size:string,durability:number){const def=artifacts.find(a=>a.id===id);const color=def?.rarity==='classified'?0xb26cff:def?.rarity==='rare'||def?.rarity==='special'?0xffcc55:0xd6f1f3;const scale=size==='coop'?1.55:size==='two-hand'?1.25:1;g.fillStyle(0x000000,.35);g.fillEllipse(x,y+12,55*scale,22*scale);g.fillStyle(color,.95);g.fillRoundedRect(x-19*scale,y-20*scale,38*scale,40*scale,9);g.lineStyle(3,durability<50?0xff5a4c:0xffffff,.65);g.strokeRoundedRect(x-19*scale,y-20*scale,38*scale,40*scale,9);g.fillStyle(0xffffff,.55);g.fillRect(x-10*scale,y-12*scale,15*scale,5*scale);}
  private drawMonster(g:Phaser.GameObjects.Graphics,x:number,y:number,id:string,state:string,elite:boolean){const def=monsters.find(m=>m.id===id);const c=Phaser.Display.Color.HexStringToColor(def?.color??'#ff5d5d').color;const pulse=1+Math.sin(this.time.now/180+x)*.08;g.fillStyle(0x000000,.35);g.fillEllipse(x,y+18,84*pulse,34*pulse);g.fillStyle(c,state==='disguised'?.55:1);const behavior=def?.behavior;if(behavior==='shadow'){g.fillEllipse(x,y,75,110);g.fillStyle(0x1a1110,.8);for(let i=0;i<5;i++)g.fillRect(x-34+i*17,y+22,9,45);}else if(behavior==='swarm'){for(let i=0;i<8;i++)g.fillTriangle(x-48+i*14,y+(i%2)*14,x-28+i*14,y-9+(i%2)*14,x-28+i*14,y+9+(i%2)*14);}else if(behavior==='juggernaut'||behavior==='guardian'){g.fillRoundedRect(x-48,y-40,96,80,18);g.fillStyle(0x1b2224,.7);g.fillRect(x-28,y-20,56,14);}else{g.fillEllipse(x,y,64*pulse,58*pulse);for(let i=0;i<4;i++)g.fillTriangle(x-22+i*15,y+22,x-30+i*15,y+55,x-12+i*15,y+48);}g.fillStyle(0xffffff,1);g.fillCircle(x-16,y-10,8);g.fillCircle(x+16,y-10,8);g.fillStyle(0x111111,1);g.fillCircle(x-16,y-10,3);g.fillCircle(x+16,y-10,3);if(elite){g.lineStyle(6,0xffc94e,.9);g.strokeCircle(x,y,62);}if(state==='stunned'){g.lineStyle(3,0x74efff,.9);g.strokeCircle(x,y,54);}}
  private drawVignette(s:GameSnapshot){const fx=this.fx;fx.clear();const me=s.players[this.dataIn.playerId]??Object.values(s.players)[0];if(!me)return;if(me.freshness<30){const alpha=(30-me.freshness)/60;fx.lineStyle(30,0xd7f8ff,alpha);fx.strokeRoundedRect(5,5,this.scale.width-10,this.scale.height-10,28);}if(s.danger>=3){fx.fillStyle(0xff2f22,.04+.02*Math.sin(this.time.now/120));fx.fillRect(0,0,this.scale.width,this.scale.height);}}
}
